"""Make movie_poster nullable in Favorite table

Revision ID: 533abcc9c43d
Revises: 
Create Date: 2024-10-13 15:40:05.387481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533abcc9c43d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_poster', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('movie_poster')

    # ### end Alembic commands ###
